"""
Support for stack-frames.

Provides Implements a nearly complete wrapper for a stack frame.
"""

from _typeshed import Incomplete

from win32comext.axdebug import gateways

class EnumDebugStackFrames(gateways.EnumDebugStackFrames):
    """
    A class that given a debugger object, can return an enumerator
    of DebugStackFrame objects.
    """
    def __init__(self, debugger) -> None: ...
    def Next(self, count): ...

class DebugStackFrame(gateways.DebugStackFrame):
    frame: Incomplete
    lineno: Incomplete
    codeContainer: Incomplete
    expressionContext: Incomplete
    def __init__(self, frame, lineno, codeContainer) -> None: ...
    def GetThread(self) -> None:
        """
        Returns the thread associated with this stack frame.

        Result must be a IDebugApplicationThread
        """
        ...
    def GetCodeContext(self): ...
    def GetDescriptionString(self, fLong): ...
    def GetLanguageString(self, fLong): ...  # type: ignore[override]
    def GetDebugProperty(self): ...

class DebugStackFrameSniffer:
    debugger: Incomplete
    def __init__(self, debugger) -> None: ...
    def EnumStackFrames(self): ...

class StackFrameDebugProperty:
    frame: Incomplete
    def __init__(self, frame) -> None: ...
    def GetPropertyInfo(self, dwFieldSpec, nRadix) -> None: ...
    def GetExtendedInfo(self) -> None: ...
    def SetValueAsString(self, value, radix) -> None: ...
    def EnumMembers(self, dwFieldSpec, nRadix, iid): ...
    def GetParent(self) -> None: ...
