from _typeshed import SupportsItems
from collections.abc import Iterable, Iterator, KeysView, Mapping, Sequence
from datetime import datetime, timedelta, tzinfo
from typing import Any as tAny
from typing_extensions import TypeAlias

from google.protobuf import struct_pb2
from google.protobuf.descriptor import Descriptor
from google.protobuf.message import Message as _Message

class Any:
    """Class for Any Message type."""
    __slots__ = ()
    type_url: str
    value: bytes
    def Pack(self, msg: _Message, type_url_prefix: str = "type.googleapis.com/", deterministic: bool | None = None) -> None: ...
    def Unpack(self, msg: _Message) -> bool: ...
    def TypeName(self) -> str: ...
    def Is(self, descriptor: Descriptor) -> bool: ...

class Timestamp:
    """Class for Timestamp message type."""
    __slots__ = ()
    def ToJsonString(self) -> str:
        """
        Converts Timestamp to RFC 3339 date string format.

        Returns:
          A string converted from timestamp. The string is always Z-normalized
          and uses 3, 6 or 9 fractional digits as required to represent the
          exact time. Example of the return format: '1972-01-01T10:00:20.021Z'
        """
        ...
    seconds: int
    nanos: int
    def FromJsonString(self, value: str) -> None: ...
    def GetCurrentTime(self) -> None: ...
    def ToNanoseconds(self) -> int: ...
    def ToMicroseconds(self) -> int: ...
    def ToMilliseconds(self) -> int: ...
    def ToSeconds(self) -> int: ...
    def FromNanoseconds(self, nanos: int) -> None: ...
    def FromMicroseconds(self, micros: int) -> None: ...
    def FromMilliseconds(self, millis: int) -> None: ...
    def FromSeconds(self, seconds: int) -> None: ...
    def ToDatetime(self, tzinfo: tzinfo | None = None) -> datetime: ...
    def FromDatetime(self, dt: datetime) -> None: ...
    def __add__(self, value: Duration | timedelta) -> datetime: ...
    def __radd__(self, value: tAny) -> datetime: ...
    def __sub__(self, value: Timestamp | Duration | timedelta) -> datetime | timedelta: ...
    def __rsub__(self, dt: datetime) -> timedelta: ...

class Duration:
    """Class for Duration message type."""
    __slots__ = ()
    def ToJsonString(self) -> str:
        """
        Converts Duration to string format.

        Returns:
          A string converted from self. The string format will contains
          3, 6, or 9 fractional digits depending on the precision required to
          represent the exact Duration value. For example: "1s", "1.010s",
          "1.000000100s", "-3.100s"
        """
        ...
    seconds: int
    nanos: int
    def FromJsonString(self, value: str) -> None: ...
    def ToNanoseconds(self) -> int: ...
    def ToMicroseconds(self) -> int: ...
    def ToMilliseconds(self) -> int: ...
    def ToSeconds(self) -> int: ...
    def FromNanoseconds(self, nanos: int) -> None: ...
    def FromMicroseconds(self, micros: int) -> None: ...
    def FromMilliseconds(self, millis: int) -> None: ...
    def FromSeconds(self, seconds: int) -> None: ...
    def ToTimedelta(self) -> timedelta: ...
    def FromTimedelta(self, td: timedelta) -> None: ...
    def __add__(self, value: Timestamp | timedelta) -> datetime | timedelta: ...
    def __radd__(self, value: tAny) -> datetime | timedelta: ...
    def __sub__(self, value: Duration | timedelta) -> timedelta: ...
    def __rsub__(self, value: datetime | timedelta) -> datetime | timedelta: ...

class FieldMask:
    """Class for FieldMask message type."""
    __slots__ = ()
    def ToJsonString(self) -> str: ...
    def FromJsonString(self, value: str) -> None: ...
    def IsValidForDescriptor(self, message_descriptor: Descriptor) -> bool: ...
    def AllFieldsFromDescriptor(self, message_descriptor: Descriptor) -> None: ...
    def CanonicalFormFromMask(self, mask: FieldMask) -> None: ...
    def Union(self, mask1: FieldMask, mask2: FieldMask) -> None: ...
    def Intersect(self, mask1: FieldMask, mask2: FieldMask) -> None: ...
    def MergeMessage(
        self, source: _Message, destination: _Message, replace_message_field: bool = False, replace_repeated_field: bool = False
    ) -> None: ...

_StructValue: TypeAlias = struct_pb2.Struct | struct_pb2.ListValue | str | float | bool | None
_StructValueArg: TypeAlias = _StructValue | Mapping[str, _StructValueArg] | Sequence[_StructValueArg]

class Struct:
    """Class for Struct message type."""
    __slots__: tuple[str, ...] = ()
    def __getitem__(self, key: str) -> _StructValue: ...
    def __setitem__(self, key: str, value: _StructValueArg) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> list[_StructValue]: ...
    def items(self) -> list[tuple[str, _StructValue]]: ...
    def get_or_create_list(self, key: str) -> struct_pb2.ListValue:
        """Returns a list for this key, creating if it didn't exist already."""
        ...
    def get_or_create_struct(self, key: str) -> struct_pb2.Struct:
        """Returns a struct for this key, creating if it didn't exist already."""
        ...
    def update(self, dictionary: SupportsItems[str, _StructValueArg]) -> None: ...

class ListValue:
    """Class for ListValue message type."""
    __slots__: tuple[str, ...] = ()
    def __len__(self) -> int: ...
    def append(self, value: _StructValue) -> None: ...
    def extend(self, elem_seq: Iterable[_StructValue]) -> None: ...
    def __getitem__(self, index: int) -> _StructValue:
        """Retrieves item by the specified index."""
        ...
    def __setitem__(self, index: int, value: _StructValueArg) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    # Doesn't actually exist at runtime; needed so type checkers understand the class is iterable
    def __iter__(self) -> Iterator[_StructValue]: ...
    def items(self) -> Iterator[_StructValue]: ...
    def add_struct(self) -> struct_pb2.Struct:
        """Appends and returns a struct value as the next value in the list."""
        ...
    def add_list(self) -> struct_pb2.ListValue:
        """Appends and returns a list value as the next value in the list."""
        ...

WKTBASES: dict[str, type[tAny]]
