from _typeshed import Incomplete

class AXEngine:
    eScript: Incomplete
    eParse: Incomplete
    eSafety: Incomplete
    def __init__(self, site, engine) -> None: ...
    def __del__(self) -> None: ...
    def GetScriptDispatch(self, name: Incomplete | None = ...): ...
    def AddNamedItem(self, item, flags): ...
    def AddCode(self, code, flags: int = ...) -> None: ...
    def EvalCode(self, code): ...
    def Start(self) -> None: ...
    def Close(self) -> None: ...
    def SetScriptState(self, state) -> None: ...

IActiveScriptSite_methods: Incomplete

class AXSite:
    """An Active Scripting site.  A Site can have exactly one engine."""
    lcid: Incomplete
    objModel: Incomplete
    engine: Incomplete
    def __init__(self, objModel=..., engine: Incomplete | None = ..., lcid: int = ...) -> None: ...
    def AddEngine(self, engine):
        """
        Adds a new engine to the site.
        engine can be a string, or a fully wrapped engine object.
        """
        ...
    def GetLCID(self): ...
    def GetItemInfo(self, name, returnMask): ...
    def GetDocVersionString(self): ...
    def OnScriptTerminate(self, result, excepInfo) -> None: ...
    def OnStateChange(self, state) -> None: ...
    def OnScriptError(self, errorInterface): ...
    def OnEnterScript(self) -> None: ...
    def OnLeaveScript(self) -> None: ...
