"""
Provides DescriptorPool to use as a container for proto2 descriptors.

The DescriptorPool is used in conjection with a DescriptorDatabase to maintain
a collection of protocol buffer descriptors for use when dynamically creating
message types at runtime.

For most applications protocol buffers should be used via modules generated by
the protocol buffer compiler tool. This should only be used when the type of
protocol buffers used in an application or library cannot be predetermined.

Below is a straightforward example on how to use this class::

  pool = DescriptorPool()
  file_descriptor_protos = [ ... ]
  for file_descriptor_proto in file_descriptor_protos:
    pool.Add(file_descriptor_proto)
  my_message_descriptor = pool.FindMessageTypeByName('some.package.MessageType')

The message descriptor can be used in conjunction with the message_factory
module in order to create a protocol buffer class that can be encoded and
decoded.

If you want to get a Python class for the specified proto, use the
helper functions inside google.protobuf.message_factory
directly instead of this class.
"""

from _typeshed import Unused
from typing import Any
from typing_extensions import Self

from .descriptor import (
    Descriptor,
    EnumDescriptor,
    FieldDescriptor,
    FileDescriptor,
    MethodDescriptor,
    OneofDescriptor,
    ServiceDescriptor,
)
from .descriptor_pb2 import FeatureSetDefaults, FileDescriptorProto

class DescriptorPool:
    def __new__(cls, descriptor_db: Any = None) -> Self: ...
    def __init__(  # pyright: ignore[reportInconsistentConstructor]
        self, descriptor_db: Any = None, use_deprecated_legacy_json_field_conflicts: Unused = False
    ) -> None: ...
    def Add(self, file_desc_proto: FileDescriptorProto) -> None: ...
    def AddSerializedFile(self, serialized_file_desc_proto: bytes) -> FileDescriptor: ...
    def FindFileByName(self, file_name: str) -> FileDescriptor: ...
    def FindFileContainingSymbol(self, symbol: str) -> FileDescriptor: ...
    def FindMessageTypeByName(self, full_name: str) -> Descriptor: ...
    def FindEnumTypeByName(self, full_name: str) -> EnumDescriptor: ...
    def FindFieldByName(self, full_name: str) -> FieldDescriptor: ...
    def FindOneofByName(self, full_name: str) -> OneofDescriptor: ...
    def FindExtensionByName(self, full_name: str) -> FieldDescriptor: ...
    def FindExtensionByNumber(self, message_descriptor: Descriptor, number: int) -> FieldDescriptor: ...
    def FindAllExtensions(self, message_descriptor: Descriptor) -> list[FieldDescriptor]: ...
    def FindServiceByName(self, full_name: str) -> ServiceDescriptor: ...
    def FindMethodByName(self, full_name: str) -> MethodDescriptor: ...
    def SetFeatureSetDefaults(self, defaults: FeatureSetDefaults) -> None: ...

def Default() -> DescriptorPool: ...
