"""Protobuf Module"""

from collections.abc import Callable, Iterable, Mapping, Sequence
from typing import Any, ClassVar, final
from typing_extensions import Self, disjoint_base

from google.protobuf.descriptor_pb2 import (
    DescriptorProto,
    EnumDescriptorProto,
    EnumOptions,
    EnumValueOptions,
    FeatureSetDefaults,
    FieldOptions,
    FileDescriptorProto,
    FileOptions,
    MessageOptions,
    MethodDescriptorProto,
    MethodOptions,
    OneofOptions,
    ServiceDescriptorProto,
    ServiceOptions,
)

default_pool: DescriptorPool

@final
class Arena: ...

@final
class Descriptor:
    containing_type: Descriptor | None
    enum_types: Sequence[EnumDescriptor]
    enum_types_by_name: Mapping[str, EnumDescriptor]
    enum_values_by_name: dict[str, EnumValueDescriptor]
    extension_ranges: list[tuple[int, int]]
    extensions: Sequence[FieldDescriptor]
    extensions_by_name: Mapping[str, FieldDescriptor]
    fields: Sequence[FieldDescriptor]
    fields_by_camelcase_name: Mapping[str, FieldDescriptor]
    fields_by_name: Mapping[str, FieldDescriptor]
    fields_by_number: Mapping[int, FieldDescriptor]
    file: FileDescriptor
    full_name: str
    has_options: bool
    is_extendable: bool
    name: str
    nested_types: Sequence[Descriptor]
    nested_types_by_name: Mapping[str, Descriptor]
    oneofs: Sequence[OneofDescriptor]
    oneofs_by_name: Mapping[str, OneofDescriptor]
    def __new__(cls, *args, **kwargs) -> Self: ...
    def CopyToProto(self, proto: DescriptorProto, /) -> None: ...
    def EnumValueName(self, enum: str, value: int) -> str: ...
    def GetOptions(self) -> MessageOptions: ...

@final
class DescriptorPool:
    def __new__(cls, *args, **kwargs) -> Self: ...
    def Add(self, file_desc_proto: FileDescriptorProto, /) -> None:
        """Adds the FileDescriptorProto and its types to this pool."""
        ...
    def AddSerializedFile(self, serialized_file_desc_proto: bytes, /) -> FileDescriptor:
        """Adds a serialized FileDescriptorProto to this pool."""
        ...
    def FindAllExtensions(self, message_descriptor: Descriptor, /) -> list[FieldDescriptor]:
        """Gets all known extensions of the given message descriptor."""
        ...
    def FindEnumTypeByName(self, full_name: str, /) -> EnumDescriptor:
        """Searches for enum type descriptor by full name."""
        ...
    def FindExtensionByName(self, full_name: str, /) -> FieldDescriptor:
        """Searches for extension descriptor by full name."""
        ...
    def FindExtensionByNumber(self, message_descriptor: Descriptor, number: int, /) -> FieldDescriptor:
        """Gets the extension descriptor for the given number."""
        ...
    def FindFieldByName(self, full_name: str, /) -> FieldDescriptor:
        """Searches for a field descriptor by full name."""
        ...
    def FindFileByName(self, file_name: str, /) -> FileDescriptor:
        """Searches for a file descriptor by its .proto name."""
        ...
    def FindFileContainingSymbol(self, symbol: str, /) -> FileDescriptor:
        """Gets the FileDescriptor containing the specified symbol."""
        ...
    def FindMessageTypeByName(self, full_name: str, /) -> Descriptor:
        """Searches for a message descriptor by full name."""
        ...
    def FindMethodByName(self, full_name: str, /) -> MethodDescriptor:
        """Searches for method descriptor by full name."""
        ...
    def FindOneofByName(self, full_name: str, /) -> OneofDescriptor:
        """Searches for oneof descriptor by full name."""
        ...
    def FindServiceByName(self, full_name: str, /) -> ServiceDescriptor:
        """Searches for service descriptor by full name."""
        ...
    def SetFeatureSetDefaults(self, defaults: FeatureSetDefaults, /) -> None:
        """Sets the default feature mappings used during the build."""
        ...

@final
class EnumDescriptor:
    containing_type: Descriptor | None
    file: FileDescriptor
    full_name: str
    has_options: bool
    is_closed: bool
    name: str
    values: Sequence[EnumValueDescriptor]
    values_by_name: Mapping[str, EnumValueDescriptor]
    values_by_number: Mapping[int, EnumValueDescriptor]
    def __new__(cls, *args, **kwargs) -> Self: ...
    def CopyToProto(self, proto: EnumDescriptorProto, /) -> None: ...
    def GetOptions(self) -> EnumOptions: ...

@final
class EnumValueDescriptor:
    has_options: bool
    index: int
    name: str
    number: int
    type: EnumDescriptor
    def __new__(cls, *args, **kwargs) -> Self: ...
    def GetOptions(self) -> EnumValueOptions: ...

@final
class ExtensionDict:
    def __contains__(self, extension_handle: FieldDescriptor, /) -> bool:
        """Return bool(key in self)."""
        ...
    def __delitem__(self, extension_handle: FieldDescriptor, /) -> None:
        """Delete self[key]."""
        ...
    def __eq__(self, other: object, /) -> bool:
        """Return self==value."""
        ...
    def __ge__(self, other: object, /) -> bool:
        """Return self>=value."""
        ...
    def __getitem__(self, extension_handle: FieldDescriptor, /) -> Any:
        """Return self[key]."""
        ...
    def __gt__(self, other: object, /) -> bool:
        """Return self>value."""
        ...
    def __iter__(self) -> ExtensionIterator:
        """Implement iter(self)."""
        ...
    def __le__(self, other: object, /) -> bool:
        """Return self<=value."""
        ...
    def __len__(self) -> int:
        """Return len(self)."""
        ...
    def __lt__(self, other: object, /) -> bool:
        """Return self<value."""
        ...
    def __ne__(self, other: object, /) -> bool:
        """Return self!=value."""
        ...
    def __setitem__(self, extension_handle: FieldDescriptor, value: Any, /) -> None:
        """Set self[key] to value."""
        ...

@final
class ExtensionIterator:
    def __iter__(self) -> Self:
        """Implement iter(self)."""
        ...
    def __next__(self) -> FieldDescriptor:
        """Implement next(self)."""
        ...

@final
class FieldDescriptor:
    CPPTYPE_BOOL: ClassVar[int] = ...
    CPPTYPE_BYTES: ClassVar[int] = ...
    CPPTYPE_DOUBLE: ClassVar[int] = ...
    CPPTYPE_ENUM: ClassVar[int] = ...
    CPPTYPE_FLOAT: ClassVar[int] = ...
    CPPTYPE_INT32: ClassVar[int] = ...
    CPPTYPE_INT64: ClassVar[int] = ...
    CPPTYPE_MESSAGE: ClassVar[int] = ...
    CPPTYPE_STRING: ClassVar[int] = ...
    CPPTYPE_UINT32: ClassVar[int] = ...
    CPPTYPE_UINT64: ClassVar[int] = ...
    LABEL_OPTIONAL: ClassVar[int] = ...
    LABEL_REPEATED: ClassVar[int] = ...
    LABEL_REQUIRED: ClassVar[int] = ...
    TYPE_BOOL: ClassVar[int] = ...
    TYPE_BYTES: ClassVar[int] = ...
    TYPE_DOUBLE: ClassVar[int] = ...
    TYPE_ENUM: ClassVar[int] = ...
    TYPE_FIXED32: ClassVar[int] = ...
    TYPE_FIXED64: ClassVar[int] = ...
    TYPE_FLOAT: ClassVar[int] = ...
    TYPE_GROUP: ClassVar[int] = ...
    TYPE_INT32: ClassVar[int] = ...
    TYPE_INT64: ClassVar[int] = ...
    TYPE_MESSAGE: ClassVar[int] = ...
    TYPE_SFIXED32: ClassVar[int] = ...
    TYPE_SFIXED64: ClassVar[int] = ...
    TYPE_SINT32: ClassVar[int] = ...
    TYPE_SINT64: ClassVar[int] = ...
    TYPE_STRING: ClassVar[int] = ...
    TYPE_UINT32: ClassVar[int] = ...
    TYPE_UINT64: ClassVar[int] = ...
    camelcase_name: str
    containing_oneof: OneofDescriptor | None
    containing_type: Descriptor | None
    cpp_type: int
    default_value: Any  # Any: str, int, float, bytes, or bool
    enum_type: EnumDescriptor | None
    extension_scope: Descriptor | None
    file: FileDescriptor
    full_name: str
    has_default_value: bool
    has_options: bool
    has_presence: bool
    index: int
    is_extension: bool
    is_packed: bool
    is_repeated: bool
    is_required: bool
    json_name: str
    message_type: Descriptor | None
    name: str
    number: int
    type: int
    def __new__(cls, *args, **kwargs) -> Self: ...
    def GetOptions(self) -> FieldOptions: ...

@final
class FileDescriptor:
    dependencies: Sequence[FileDescriptor]
    enum_types_by_name: Mapping[str, EnumDescriptor]
    extensions_by_name: Mapping[str, FieldDescriptor]
    has_options: bool
    message_types_by_name: Mapping[str, Descriptor]
    name: str
    package: str
    pool: DescriptorPool
    public_dependencies: Sequence[FileDescriptor]
    serialized_pb: bytes
    services_by_name: Mapping[str, ServiceDescriptor]
    def __new__(cls, *args, **kwargs) -> Self: ...
    def CopyToProto(self, proto: FileDescriptorProto, /) -> None: ...
    def GetOptions(self) -> FileOptions: ...

@final
class MapIterator:
    def __iter__(self) -> Self:
        """Implement iter(self)."""
        ...
    def __next__(self) -> bool | int | str:
        """Implement next(self)."""
        ...

@final
class Message:
    """A ProtocolMessage"""
    Extensions: ExtensionDict
    def __init__(self, *args, **kwargs) -> None: ...
    def __contains__(self, field_name_or_key: str, /) -> bool:
        """Checks if a message field is set."""
        ...
    def __deepcopy__(self, memo: Any = None) -> Self:
        """Makes a deep copy of the class."""
        ...
    def __delattr__(self, name: str, /) -> None:
        """Implement delattr(self, name)."""
        ...
    def __eq__(self, other: object, /) -> bool:
        """Return self==value."""
        ...
    def __ge__(self, other: object, /) -> bool:
        """Return self>=value."""
        ...
    def __gt__(self, other: object, /) -> bool:
        """Return self>value."""
        ...
    def __le__(self, other: object, /) -> bool:
        """Return self<=value."""
        ...
    def __lt__(self, other: object, /) -> bool:
        """Return self<value."""
        ...
    def __ne__(self, other: object, /) -> bool:
        """Return self!=value."""
        ...
    def __setattr__(self, name: str, value: Any, /) -> None:
        """Implement setattr(self, name, value)."""
        ...
    def MergeFrom(self, other_msg: Message, /) -> None:
        """Merges a protocol message into the current message."""
        ...
    def CopyFrom(self, other_msg: Message, /) -> None:
        """Copies a protocol message into the current message."""
        ...
    def Clear(self) -> None:
        """Clears the message."""
        ...
    def SetInParent(self) -> None:
        """Sets the has bit of the given field in its parent message."""
        ...
    def IsInitialized(self, errors: list[str] | None = None) -> bool:
        """Checks if all required fields of a protocol message are set."""
        ...
    def MergeFromString(self, serialized: bytes, /) -> int:
        """Merges a serialized message into the current message."""
        ...
    def ParseFromString(self, serialized: bytes, /) -> int:
        """Parses a serialized message into the current message."""
        ...
    def SerializeToString(self, *, deterministic: bool = ...) -> bytes:
        """Serializes the message to a string, only for initialized messages."""
        ...
    def SerializePartialToString(self, *, deterministic: bool = ...) -> bytes:
        """Serializes the message to a string, even if it isn't initialized."""
        ...
    def ListFields(self) -> list[tuple[FieldDescriptor, Any]]:
        """Lists all set fields of a message."""
        ...
    def HasField(self, field_name: str, /) -> bool:
        """Checks if a message field is set."""
        ...
    def ClearField(self, field_name: str, /) -> None:
        """Clears a message field."""
        ...
    def WhichOneof(self, oneof_group: str, /) -> str | None:
        """Returns the name of the field set inside a oneof, or None if no field is set."""
        ...
    def HasExtension(self, field_descriptor: FieldDescriptor, /) -> bool:
        """Checks if a message field is set."""
        ...
    def ClearExtension(self, field_descriptor: FieldDescriptor, /) -> None:
        """Clears a message field."""
        ...
    def UnknownFields(self) -> UnknownFieldSet:
        """Parse unknown field set"""
        ...
    def DiscardUnknownFields(self) -> None:
        """Discards the unknown fields."""
        ...
    def ByteSize(self) -> int:
        """Returns the size of the message in bytes."""
        ...
    @classmethod
    def FromString(cls, s: bytes, /) -> Self:
        """Creates new method instance from given serialized data."""
        ...
    def FindInitializationErrors(self) -> list[str]:
        """Finds unset required fields."""
        ...

@disjoint_base
class MessageMeta(type): ...

@final
class MethodDescriptor:
    client_streaming: bool
    containing_service: ServiceDescriptor
    full_name: str
    has_options: bool
    index: int
    input_type: Descriptor
    name: str
    output_type: Descriptor
    server_streaming: bool
    def __new__(cls, *args, **kwargs) -> Self: ...
    def CopyToProto(self, proto: MethodDescriptorProto, /) -> None: ...
    def GetOptions(self) -> MethodOptions: ...

@final
class OneofDescriptor:
    containing_type: Descriptor
    fields: Sequence[FieldDescriptor]
    full_name: str
    has_options: bool
    index: int
    name: str
    def __new__(cls, *args, **kwargs) -> Self: ...
    def GetOptions(self) -> OneofOptions: ...

@final
class RepeatedCompositeContainer:
    def __new__(cls, *args, **kwargs) -> Self: ...
    def MergeFrom(self, other: RepeatedCompositeContainer | Iterable[Message], /) -> None:
        """Adds objects to the repeated container."""
        ...
    def add(self, **kwargs: Any) -> Message:
        """Adds an object to the repeated container."""
        ...
    def append(self, value: Message, /) -> None:
        """Appends a message to the end of the repeated container."""
        ...
    def extend(self, values: Iterable[Message], /) -> None:
        """Adds objects to the repeated container."""
        ...
    def insert(self, key: int, value: Message, /) -> None:
        """Inserts a message before the specified index."""
        ...
    def pop(self, key: int = -1, /) -> Message:
        """Removes an object from the repeated container and returns it."""
        ...
    def remove(self, value: Message, /) -> None:
        """Removes an object from the repeated container."""
        ...
    def reverse(self) -> None:
        """Reverses elements order of the repeated container."""
        ...
    def sort(self, *, key: Callable[[Any], Any] | None = None, reverse: bool = False) -> None:
        """Sorts the repeated container."""
        ...
    def clear(self) -> None:
        """Clears repeated container."""
        ...
    def __deepcopy__(self, memo: Any = None) -> RepeatedCompositeContainer:
        """Makes a deep copy of the class."""
        ...
    def __delitem__(self, key: int | slice, /) -> None:
        """Delete self[key]."""
        ...
    def __eq__(self, other: object, /) -> bool:
        """Return self==value."""
        ...
    def __ge__(self, other: object, /) -> bool:
        """Return self>=value."""
        ...
    def __getitem__(self, index: int | slice, /) -> Message:
        """Return self[key]."""
        ...
    def __gt__(self, other: object, /) -> bool:
        """Return self>value."""
        ...
    def __le__(self, other: object, /) -> bool:
        """Return self<=value."""
        ...
    def __len__(self) -> int:
        """Return len(self)."""
        ...
    def __lt__(self, other: object, /) -> bool:
        """Return self<value."""
        ...
    def __ne__(self, other: object, /) -> bool:
        """Return self!=value."""
        ...
    def __setitem__(self, index: int | slice, value: Message, /) -> None:
        """Set self[key] to value."""
        ...

@final
class RepeatedScalarContainer:
    def __new__(cls, *args, **kwargs) -> Self: ...
    def MergeFrom(self, other: Any, /) -> None:
        """Merges a repeated container into the current container."""
        ...
    def append(self, value: Any, /) -> None:
        """Appends an object to the repeated container."""
        ...
    def extend(self, values: Any, /) -> None:
        """Appends objects to the repeated container."""
        ...
    def insert(self, key: int, value: Any, /) -> None:
        """Inserts an object at the specified position in the container."""
        ...
    def pop(self, key: int = -1, /) -> Any:
        """Removes an object from the repeated container and returns it."""
        ...
    def remove(self, value: Any, /) -> None:
        """Removes an object from the repeated container."""
        ...
    def reverse(self) -> None:
        """Reverses elements order of the repeated container."""
        ...
    def sort(self, *, key: Callable[[Any], Any] | None = None, reverse: bool = False) -> None:
        """Sorts the repeated container."""
        ...
    def clear(self) -> None:
        """Clears repeated container."""
        ...
    def __array__(self, dtype: Any = None, copy: bool | None = None) -> Any:
        """Returns a np.array."""
        ...
    def __deepcopy__(self, memo: Any = None) -> RepeatedScalarContainer:
        """Makes a deep copy of the class."""
        ...
    def __delitem__(self, key: int | slice, /) -> None:
        """Delete self[key]."""
        ...
    def __eq__(self, other: object, /) -> bool:
        """Return self==value."""
        ...
    def __ge__(self, other: object, /) -> bool:
        """Return self>=value."""
        ...
    def __getitem__(self, index: int | slice, /) -> Any:
        """Return self[key]."""
        ...
    def __gt__(self, other: object, /) -> bool:
        """Return self>value."""
        ...
    def __le__(self, other: object, /) -> bool:
        """Return self<=value."""
        ...
    def __len__(self) -> int:
        """Return len(self)."""
        ...
    def __lt__(self, other: object, /) -> bool:
        """Return self<value."""
        ...
    def __ne__(self, other: object, /) -> bool:
        """Return self!=value."""
        ...
    def __reduce__(self) -> tuple[Any, ...]:
        """Outputs picklable representation of the repeated field."""
        ...
    def __setitem__(self, index: int | slice, value: Any, /) -> None:
        """Set self[key] to value."""
        ...

@final
class ServiceDescriptor:
    file: FileDescriptor
    full_name: str
    has_options: bool
    index: int
    methods: Sequence[MethodDescriptor]
    methods_by_name: Mapping[str, MethodDescriptor]
    name: str
    def __new__(cls, *args, **kwargs) -> Self: ...
    def CopyToProto(self, proto: ServiceDescriptorProto, /) -> None: ...
    def FindMethodByName(self, name: str, /) -> MethodDescriptor: ...
    def GetOptions(self) -> ServiceOptions: ...

@final
class UnknownFieldSet:
    def __new__(cls, *args, **kwargs) -> Self: ...
    def __getitem__(self, index: int, /) -> Any:
        """Return self[key]."""
        ...
    def __len__(self) -> int:
        """Return len(self)."""
        ...

def SetAllowOversizeProtos(allow: bool, /) -> None:
    """Enable/disable oversize proto parsing."""
    ...
