import enum
from _typeshed import Incomplete
from collections.abc import Generator
from typing import Final
from typing_extensions import Self

from kafka.future import Future

MAX_TIMEOUT: Final = 2147483

def yield_callback(callback): ...

class KernelEvent:
    method: str
    args: tuple[Incomplete, ...]
    def __init__(self, method: str, *args) -> None: ...
    def __await__(self) -> Generator[Self]: ...

class TaskState(enum.Enum):
    """An enumeration."""
    CREATED = "created"
    SCHEDULED = "scheduled"
    UNSCHEDULED = "unscheduled"
    READY = "ready"
    RUNNING = "running"
    WAIT_IO = "wait_io"
    WAIT_FUTURE = "wait_future"
    DONE = "done"
    CANCELLED = "cancelled"

class Task:
    scheduled_at: Incomplete | None
    state: Incomplete
    def __init__(self, coro) -> None: ...
    def __lt__(self, other) -> bool: ...
    def __call__(self, arg=None): ...
    def push_stack(self, coro) -> None: ...
    def inject_exc(self, exc) -> None: ...
    def close(self) -> None: ...
    @property
    def is_done(self) -> bool: ...
    @property
    def result(self): ...
    @property
    def exception(self): ...

class NetworkSelector:
    DEFAULT_CONFIG: dict[str, Incomplete]
    config: dict[str, Incomplete]
    def __init__(self, **configs) -> None: ...
    def run_forever(self) -> None:
        """
        Run the event loop until stop() is called. Intended to be driven by
        a dedicated IO thread. Wake-ups from other threads must go through
        call_soon_threadsafe() so the select() loop returns promptly.
        """
        ...
    def start(self) -> None:
        """Spawn a daemon IO thread that owns the event loop. Idempotent."""
        ...
    def stop(self, timeout_ms=None) -> None:
        """
        Signal run_forever() to exit and join the IO thread.

        Blocks the caller until the IO thread terminates (or ``timeout_ms``
        elapses). Pending cross-thread ``run()`` waiters are failed with
        KafkaConnectionError. Idempotent; safe to call from any thread
        other than the IO thread itself.
        """
        ...
    def run(self, coro, *args):
        """
        Schedules coro on the event loop, blocks until complete, returns value or raises.

        If an IO thread is running (via start()), the caller thread blocks on
        a cross-thread Event while the coroutine runs on the IO thread. Safe
        to call concurrently from multiple caller threads.

        If no IO thread is running, falls back to driving the loop on the
        caller thread (legacy behavior).
        """
        ...
    def drain(self, scheduled: bool = False) -> None: ...
    def call_at(self, when, task) -> Task: ...
    def call_later(self, delay, task) -> Task: ...
    def call_soon(self, task) -> Task: ...
    def call_soon_threadsafe(self, callback) -> Task: ...
    def call_soon_with_future(self, coro, *args) -> Future: ...
    def cancel(self, task) -> None: ...
    def reschedule(self, when, task): ...
    def sleep(self, delay) -> KernelEvent: ...
    def wait_write(self, fileobj, timeout_at=None) -> KernelEvent: ...
    def wait_read(self, fileobj, timeout_at=None) -> KernelEvent: ...
    def register_event(self, fileobj, event, task) -> None: ...
    def unregister_event(self, fileobj, event) -> None: ...
    def add_reader(self, fileobj, task) -> None: ...
    def remove_reader(self, fileobj) -> None: ...
    def add_writer(self, fileobj, task) -> None: ...
    def remove_writer(self, fileobj) -> None: ...
    def poll(self, timeout_ms=None, future=None) -> None: ...
    def wakeup(self) -> None: ...
    def close(self) -> None: ...
