"""Read/write support for Maildir, mbox, MH, Babyl, and MMDF mailboxes."""

import email.message
import io
import sys
from _typeshed import StrPath, SupportsItems, SupportsNoArgReadline, SupportsRead, SupportsWrite, Unused
from abc import ABCMeta, abstractmethod
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from types import GenericAlias, TracebackType
from typing import Any, Generic, Literal, Protocol, TypeVar, overload, type_check_only
from typing_extensions import Self, TypeAlias

__all__ = [
    "Mailbox",
    "Maildir",
    "mbox",
    "MH",
    "Babyl",
    "MMDF",
    "Message",
    "MaildirMessage",
    "mboxMessage",
    "MHMessage",
    "BabylMessage",
    "MMDFMessage",
    "Error",
    "NoSuchMailboxError",
    "NotEmptyError",
    "ExternalClashError",
    "FormatError",
]

_T = TypeVar("_T")

@type_check_only
class _SupportsReadAndReadline(SupportsRead[bytes], SupportsNoArgReadline[bytes], Protocol): ...

# As opposed to _MessageT_co in email._policybase, this type is bound to
# mailbox.Message instead of email.message.Message.
_MessageT_co = TypeVar("_MessageT_co", bound=Message, default=Message, covariant=True)

_MessageData: TypeAlias = email.message.Message | bytes | str | io.StringIO | _SupportsReadAndReadline

@type_check_only
class _HasIteritems(Protocol):
    def iteritems(self) -> Iterator[tuple[str, _MessageData]]: ...

linesep: bytes

# Common interface for get_file() return types.
@type_check_only
class _GetFileReturn(Protocol):
    def __iter__(self) -> Iterator[bytes]: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None, /
    ) -> bool | None: ...
    def read(self, size: int | None = None, /) -> bytes: ...
    def read1(self, size: int | None = None, /) -> bytes: ...
    def readline(self, size: int | None = None, /) -> bytes: ...
    def readlines(self, sizehint: int | None = None, /) -> list[bytes]: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int = 0, /) -> object: ...
    def close(self) -> object: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def flush(self) -> object: ...
    @property
    def closed(self) -> bool: ...

class Mailbox(Generic[_MessageT_co]):
    _path: str  # undocumented
    _factory: Callable[[_GetFileReturn], _MessageT_co] | None  # undocumented
    @overload
    def __init__(self, path: StrPath, factory: Callable[[_GetFileReturn], _MessageT_co], create: bool = True) -> None: ...
    @overload
    def __init__(self, path: StrPath, factory: None = None, create: bool = True) -> None:
        """Initialize a Mailbox instance."""
        ...
    @abstractmethod
    def add(self, message: _MessageData) -> str:
        """Add message and return assigned key."""
        ...
    @abstractmethod
    def remove(self, key: str) -> None:
        """Remove the keyed message; raise KeyError if it doesn't exist."""
        ...
    def __delitem__(self, key: str) -> None: ...
    def discard(self, key: str) -> None:
        """If the keyed message exists, remove it."""
        ...
    @abstractmethod
    def __setitem__(self, key: str, message: _MessageData) -> None:
        """Replace the keyed message; raise KeyError if it doesn't exist."""
        ...
    @overload
    def get(self, key: str, default: None = None) -> _MessageT_co | None: ...
    @overload
    def get(self, key: str, default: _T) -> _MessageT_co | _T: ...
    def __getitem__(self, key: str) -> _MessageT_co: ...
    @abstractmethod
    def get_message(self, key: str) -> _MessageT_co: ...
    def get_string(self, key: str) -> str: ...
    @abstractmethod
    def get_bytes(self, key: str) -> bytes: ...
    @abstractmethod
    def get_file(self, key: str) -> _GetFileReturn: ...
    @abstractmethod
    def iterkeys(self) -> Iterator[str]: ...
    def keys(self) -> list[str]: ...
    def itervalues(self) -> Iterator[_MessageT_co]: ...
    def __iter__(self) -> Iterator[_MessageT_co]: ...
    def values(self) -> list[_MessageT_co]: ...
    def iteritems(self) -> Iterator[tuple[str, _MessageT_co]]: ...
    def items(self) -> list[tuple[str, _MessageT_co]]: ...
    @abstractmethod
    def __contains__(self, key: str) -> bool:
        """Return True if the keyed message exists, False otherwise."""
        ...
    @abstractmethod
    def __len__(self) -> int:
        """Return a count of messages in the mailbox."""
        ...
    def clear(self) -> None:
        """Delete all messages."""
        ...
    @overload
    def pop(self, key: str, default: None = None) -> _MessageT_co | None: ...
    @overload
    def pop(self, key: str, default: _T) -> _MessageT_co | _T: ...
    def popitem(self) -> tuple[str, _MessageT_co]: ...
    def update(
        self, arg: _HasIteritems | SupportsItems[str, _MessageData] | Iterable[tuple[str, _MessageData]] | None = None
    ) -> None: ...
    @abstractmethod
    def flush(self) -> None:
        """Write any pending changes to the disk."""
        ...
    @abstractmethod
    def lock(self) -> None:
        """Lock the mailbox."""
        ...
    @abstractmethod
    def unlock(self) -> None:
        """Unlock the mailbox if it is locked."""
        ...
    @abstractmethod
    def close(self) -> None: ...
    # Undocumented, called by subclasses to parse added messages.
    def _dump_message(self, message: _MessageData, target: SupportsWrite[bytes], mangle_from_: bool = False) -> None: ...
    def __class_getitem__(cls, item: Any, /) -> GenericAlias: ...

class Maildir(Mailbox[MaildirMessage]):
    """A qmail-style Maildir mailbox."""
    colon: str
    def __init__(
        self, dirname: StrPath, factory: Callable[[_GetFileReturn], MaildirMessage] | None = None, create: bool = True
    ) -> None: ...
    def add(self, message: _MessageData | MaildirMessage) -> str: ...
    def remove(self, key: str) -> None: ...
    def __setitem__(self, key: str, message: _MessageData | MaildirMessage) -> None: ...
    def get_message(self, key: str) -> MaildirMessage: ...
    def get_bytes(self, key: str) -> bytes: ...
    def get_file(self, key: str) -> _ProxyFile: ...
    if sys.version_info >= (3, 13):
        def get_info(self, key: str) -> str:
            """Get the keyed message's "info" as a string."""
            ...
        def set_info(self, key: str, info: str) -> None:
            """Set the keyed message's "info" string."""
            ...
        def get_flags(self, key: str) -> str:
            """Return as a string the standard flags that are set on the keyed message."""
            ...
        def set_flags(self, key: str, flags: str) -> None:
            """Set the given flags and unset all others on the keyed message."""
            ...
        def add_flag(self, key: str, flag: str) -> None:
            """Set the given flag(s) without changing others on the keyed message."""
            ...
        def remove_flag(self, key: str, flag: str) -> None:
            """Unset the given string flag(s) without changing others on the keyed message."""
            ...

    def iterkeys(self) -> Iterator[str]:
        """Return an iterator over keys."""
        ...
    def __contains__(self, key: str) -> bool:
        """Return True if the keyed message exists, False otherwise."""
        ...
    def __len__(self) -> int:
        """Return a count of messages in the mailbox."""
        ...
    def flush(self) -> None:
        """Write any pending changes to disk."""
        ...
    def lock(self) -> None:
        """Lock the mailbox."""
        ...
    def unlock(self) -> None:
        """Unlock the mailbox if it is locked."""
        ...
    def close(self) -> None:
        """Flush and close the mailbox."""
        ...
    def list_folders(self) -> list[str]:
        """Return a list of folder names."""
        ...
    def get_folder(self, folder: str) -> Maildir:
        """Return a Maildir instance for the named folder."""
        ...
    def add_folder(self, folder: str) -> Maildir:
        """Create a folder and return a Maildir instance representing it."""
        ...
    def remove_folder(self, folder: str) -> None:
        """Delete the named folder, which must be empty."""
        ...
    def clean(self) -> None:
        """Delete old files in "tmp"."""
        ...
    def next(self) -> str | None:
        """Return the next message in a one-time iteration."""
        ...

class _singlefileMailbox(Mailbox[_MessageT_co], metaclass=ABCMeta):
    def add(self, message: _MessageData) -> str: ...
    def remove(self, key: str) -> None: ...
    def __setitem__(self, key: str, message: _MessageData) -> None: ...
    def iterkeys(self) -> Iterator[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...

class _mboxMMDF(_singlefileMailbox[_MessageT_co]):
    def get_message(self, key: str) -> _MessageT_co: ...
    def get_file(self, key: str, from_: bool = False) -> _PartialFile: ...
    def get_bytes(self, key: str, from_: bool = False) -> bytes: ...
    def get_string(self, key: str, from_: bool = False) -> str: ...

class mbox(_mboxMMDF[mboxMessage]):
    def __init__(
        self, path: StrPath, factory: Callable[[_GetFileReturn], mboxMessage] | None = None, create: bool = True
    ) -> None: ...

class MMDF(_mboxMMDF[MMDFMessage]):
    def __init__(
        self, path: StrPath, factory: Callable[[_GetFileReturn], MMDFMessage] | None = None, create: bool = True
    ) -> None: ...

class MH(Mailbox[MHMessage]):
    def __init__(
        self, path: StrPath, factory: Callable[[_GetFileReturn], MHMessage] | None = None, create: bool = True
    ) -> None: ...
    def add(self, message: _MessageData) -> str: ...
    def remove(self, key: str) -> None: ...
    def __setitem__(self, key: str, message: _MessageData) -> None: ...
    def get_message(self, key: str) -> MHMessage: ...
    def get_bytes(self, key: str) -> bytes: ...
    def get_file(self, key: str) -> _ProxyFile: ...
    def iterkeys(self) -> Iterator[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def flush(self) -> None: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def close(self) -> None: ...
    def list_folders(self) -> list[str]: ...
    def get_folder(self, folder: StrPath) -> MH: ...
    def add_folder(self, folder: StrPath) -> MH: ...
    def remove_folder(self, folder: StrPath) -> None: ...
    def get_sequences(self) -> dict[str, list[int]]: ...
    def set_sequences(self, sequences: Mapping[str, Sequence[int]]) -> None: ...
    def pack(self) -> None: ...

class Babyl(_singlefileMailbox[BabylMessage]):
    def __init__(
        self, path: StrPath, factory: Callable[[_GetFileReturn], BabylMessage] | None = None, create: bool = True
    ) -> None: ...
    def get_message(self, key: str) -> BabylMessage: ...
    def get_bytes(self, key: str) -> bytes: ...
    def get_file(self, key: str) -> io.BytesIO: ...
    def get_labels(self) -> list[str]: ...

class Message(email.message.Message[str, str]):
    def __init__(self, message: _MessageData | None = None) -> None: ...

class MaildirMessage(Message):
    """Message with Maildir-specific properties."""
    def get_subdir(self) -> str:
        """Return 'new' or 'cur'."""
        ...
    def set_subdir(self, subdir: Literal["new", "cur"]) -> None:
        """Set subdir to 'new' or 'cur'."""
        ...
    def get_flags(self) -> str:
        """Return as a string the flags that are set."""
        ...
    def set_flags(self, flags: Iterable[str]) -> None:
        """Set the given flags and unset all others."""
        ...
    def add_flag(self, flag: str) -> None:
        """Set the given flag(s) without changing others."""
        ...
    def remove_flag(self, flag: str) -> None:
        """Unset the given string flag(s) without changing others."""
        ...
    def get_date(self) -> int:
        """Return delivery date of message, in seconds since the epoch."""
        ...
    def set_date(self, date: float) -> None:
        """Set delivery date of message, in seconds since the epoch."""
        ...
    def get_info(self) -> str:
        """Get the message's "info" as a string."""
        ...
    def set_info(self, info: str) -> None:
        """Set the message's "info" string."""
        ...

class _mboxMMDFMessage(Message):
    """Message with mbox- or MMDF-specific properties."""
    def get_from(self) -> str:
        """Return contents of "From " line."""
        ...
    def set_from(self, from_: str, time_: bool | tuple[int, int, int, int, int, int, int, int, int] | None = None) -> None:
        """Set "From " line, formatting and appending time_ if specified."""
        ...
    def get_flags(self) -> str:
        """Return as a string the flags that are set."""
        ...
    def set_flags(self, flags: Iterable[str]) -> None:
        """Set the given flags and unset all others."""
        ...
    def add_flag(self, flag: str) -> None:
        """Set the given flag(s) without changing others."""
        ...
    def remove_flag(self, flag: str) -> None:
        """Unset the given string flag(s) without changing others."""
        ...

class mboxMessage(_mboxMMDFMessage):
    """Message with mbox-specific properties."""
    ...

class MHMessage(Message):
    """Message with MH-specific properties."""
    def get_sequences(self) -> list[str]:
        """Return a list of sequences that include the message."""
        ...
    def set_sequences(self, sequences: Iterable[str]) -> None:
        """Set the list of sequences that include the message."""
        ...
    def add_sequence(self, sequence: str) -> None:
        """Add sequence to list of sequences including the message."""
        ...
    def remove_sequence(self, sequence: str) -> None:
        """Remove sequence from the list of sequences including the message."""
        ...

class BabylMessage(Message):
    """Message with Babyl-specific properties."""
    def get_labels(self) -> list[str]:
        """Return a list of labels on the message."""
        ...
    def set_labels(self, labels: Iterable[str]) -> None:
        """Set the list of labels on the message."""
        ...
    def add_label(self, label: str) -> None:
        """Add label to list of labels on the message."""
        ...
    def remove_label(self, label: str) -> None:
        """Remove label from the list of labels on the message."""
        ...
    def get_visible(self) -> Message:
        """Return a Message representation of visible headers."""
        ...
    def set_visible(self, visible: _MessageData) -> None:
        """Set the Message representation of visible headers."""
        ...
    def update_visible(self) -> None:
        """Update and/or sensibly generate a set of visible headers."""
        ...

class MMDFMessage(_mboxMMDFMessage):
    """Message with MMDF-specific properties."""
    ...

# Until Python 3.14, this class was technically - but unnecessarily - generic at runtime.
class _ProxyFile:
    def __init__(self, f: _GetFileReturn, pos: int | None = None) -> None: ...
    def read(self, size: int | None = None) -> bytes: ...
    def read1(self, size: int | None = None) -> bytes: ...
    def readline(self, size: int | None = None) -> bytes: ...
    def readlines(self, sizehint: int | None = None) -> list[bytes]: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int = 0) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: Unused) -> None: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def flush(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __class_getitem__(cls, item: Any, /) -> GenericAlias:
        """
        Represent a PEP 585 generic type

        E.g. for t = list[int], t.__origin__ is list and t.__args__ is (int,).
        """
        ...

class _PartialFile(_ProxyFile):
    def __init__(self, f: _GetFileReturn, start: int | None = None, stop: int | None = None) -> None: ...

class Error(Exception):
    """Raised for module-specific errors."""
    ...
class NoSuchMailboxError(Error):
    """The specified mailbox does not exist and won't be created."""
    ...
class NotEmptyError(Error):
    """The specified mailbox is not empty and deletion was requested."""
    ...
class ExternalClashError(Error):
    """Another process caused an action to fail."""
    ...
class FormatError(Error):
    """A file appears to have an invalid format."""
    ...
