from logging import Logger

from aws_xray_sdk.core.daemon_config import DaemonConfig

log: Logger

class DefaultSampler:
    """
    Making sampling decisions based on centralized sampling rules defined
    by X-Ray control plane APIs. It will fall back to local sampler if
    centralized sampling rules are not available.
    """
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def should_trace(self, sampling_req=None): ...
    def load_local_rules(self, rules) -> None: ...
    def load_settings(self, daemon_config: DaemonConfig, context, origin=None) -> None: ...

    @property
    def xray_client(self): ...
    @xray_client.setter
    def xray_client(self, v) -> None: ...
