import types
from collections.abc import Callable, Collection, Iterable, Iterator, Mapping
from functools import cached_property
from types import TracebackType
from typing import Any, TypeAlias
from typing_extensions import Self
from urllib.request import Request

from yt_dlp.cache import Cache
from yt_dlp.cookies import YoutubeDLCookieJar
from yt_dlp.networking import RequestDirector, RequestHandler, Response
from yt_dlp.utils import Namespace

from . import _YoutubeDLOptions
from .extractor.common import InfoExtractor, _InfoDict
from .postprocessor.common import PostProcessor
from .utils._utils import _ProgressState

_FormatSelector: TypeAlias = Callable[[Mapping[str, Any]], Iterator[Any]]

class YoutubeDL:
    params: _YoutubeDLOptions
    cache: Cache
    format_selector: _FormatSelector
    archive: set[str]
    def __init__(self, params: _YoutubeDLOptions | None = None, auto_init: bool = True) -> None: ...
    def warn_if_short_id(self, argv: list[str]) -> None: ...
    def add_info_extractor(self, ie: InfoExtractor) -> None:
        """Add an InfoExtractor object to the end of the list."""
        ...
    def get_info_extractor(self, ie_key: str) -> InfoExtractor:
        """
        Get an instance of an IE with name ie_key, it will try to get one from
        the _ies list, if there's no instance it will create a new one and add
        it to the extractor list.
        """
        ...
    def add_default_info_extractors(self) -> None:
        """Add the InfoExtractors returned by gen_extractors to the end of the list"""
        ...
    def add_post_processor(self, pp: PostProcessor, when: str = "post_process") -> None:
        """Add a PostProcessor object to the end of the chain."""
        ...
    def add_post_hook(self, ph: Callable[..., object]) -> None:
        """Add the post hook"""
        ...
    def add_close_hook(self, ch: Callable[..., object]) -> None:
        """Add a close hook, called when YoutubeDL.close() is called"""
        ...
    def add_progress_hook(self, ph: Callable[..., object]) -> None:
        """Add the download progress hook"""
        ...
    def add_postprocessor_hook(self, ph: Callable[..., object]) -> None:
        """Add the postprocessing progress hook"""
        ...
    def to_stdout(self, message: str, skip_eol: bool = False, quiet: bool | None = None) -> None:
        """Print message to stdout"""
        ...
    def to_screen(self, message: str, skip_eol: bool = False, quiet: bool | None = None, only_once: bool = False) -> None:
        """Print message to screen if not in quiet mode"""
        ...
    def to_stderr(self, message: str, only_once: bool = False) -> None:
        """Print message to stderr"""
        ...
    def to_console_title(
        self, message: str | None = None, progress_state: _ProgressState | None = None, percent: int | None = None
    ) -> None: ...
    def save_console_title(self) -> None: ...
    def restore_console_title(self) -> None: ...
    def __enter__(self) -> Self: ...
    def save_cookies(self) -> None: ...
    def __exit__(self, *args: object) -> None: ...
    def close(self) -> None: ...
    def trouble(self, message: str | None = None, tb: TracebackType | None = None, is_error: bool = True) -> None:
        """
        Determine action to take when a download problem appears.

        Depending on if the downloader has been configured to ignore
        download errors or not, this method may throw an exception or
        not when errors are found, after printing the message.

        @param tb          If given, is additional traceback information
        @param is_error    Whether to raise error according to ignorerrors
        """
        ...
    Styles: Namespace
    def report_warning(self, message: str, only_once: bool = False) -> None:
        """
        Print the message to stderr, it will be prefixed with 'WARNING:'
        If stderr is a tty file the 'WARNING:' will be colored
        """
        ...
    def deprecation_warning(self, message: str, *, stacklevel: int = 0) -> None: ...
    def deprecated_feature(self, message: str) -> None: ...
    def report_error(self, message: str, tb: types.TracebackType | None = None, is_error: bool = True) -> None:
        """
        Do the same as trouble, but prefixes the message with 'ERROR:', colored
        in red if stderr is a tty file.
        """
        ...
    def write_debug(self, message: str, only_once: bool = False) -> None:
        """Log debug message or Print message to stderr"""
        ...
    def report_file_already_downloaded(self, file_name: str) -> None:
        """Report file has already been fully downloaded."""
        ...
    def report_file_delete(self, file_name: str) -> None:
        """Report that existing file will be deleted."""
        ...
    def raise_no_formats(self, info: str, forced: bool = False, *, msg: str | None = None) -> None: ...
    def get_output_path(self, dir_type: str = "", filename: str | None = None) -> str: ...
    @staticmethod
    def escape_outtmpl(outtmpl: str) -> str:
        """Escape any remaining strings like %s, %abc% etc. """
        ...
    @classmethod
    def validate_outtmpl(cls, outtmpl: str) -> ValueError | None:
        """@return None or Exception object """
        ...
    def prepare_outtmpl(
        self, outtmpl: str, info_dict: _InfoDict, sanitize: bool = False, *, _exec: bool = False
    ) -> tuple[str, dict[str, Any]]:
        """
        Make the outtmpl and info_dict suitable for substitution: ydl.escape_outtmpl(outtmpl) % info_dict
        @param sanitize    Whether to sanitize the output as a filename
        """
        ...
    def evaluate_outtmpl(self, outtmpl: str, info_dict: _InfoDict, sanitize: bool = False) -> str: ...
    def prepare_filename(
        self, info_dict: _InfoDict, dir_type: str = "", *, outtmpl: str | None = None, warn: bool = False
    ) -> str:
        """Generate the output filename"""
        ...
    @staticmethod
    def add_extra_info(info_dict: _InfoDict, extra_info: Mapping[str, Any]) -> None:
        """Set the keys from extra_info in info dict if they are missing"""
        ...
    def extract_info(
        self,
        url: str,
        download: bool = True,
        ie_key: str | None = None,
        extra_info: Any | None = None,
        process: bool = True,
        force_generic_extractor: bool = False,
    ) -> _InfoDict:
        """
        Extract and return the information dictionary of the URL

        Arguments:
        @param url          URL to extract

        Keyword arguments:
        @param download     Whether to download videos
        @param process      Whether to resolve all unresolved references (URLs, playlist items).
                            Must be True for download to work
        @param ie_key       Use only the extractor with this key

        @param extra_info   Dictionary containing the extra values to add to the info (For internal use only)
        @force_generic_extractor  Force using the generic extractor (Deprecated; use ie_key='Generic')
        """
        ...
    def add_default_extra_info(self, ie_result: _InfoDict, ie: InfoExtractor, url: str) -> None: ...
    def process_ie_result(
        self, ie_result: _InfoDict, download: bool = True, extra_info: Mapping[str, Any] | None = None
    ) -> _InfoDict:
        """
        Take the result of the ie(may be modified) and resolve all unresolved
        references (URLs, playlist items).

        It will also download the videos if 'download'.
        Returns the resolved ie_result.
        """
        ...
    def build_format_selector(self, format_spec: str) -> _FormatSelector: ...
    def sort_formats(self, info_dict: _InfoDict) -> None: ...
    def process_video_result(self, info_dict: _InfoDict, download: bool = True) -> _InfoDict: ...
    def process_subtitles(
        self, video_id: str, normal_subtitles: Mapping[str, Any], automatic_captions: Mapping[str, Any]
    ) -> dict[str, Any] | None:
        """Select the requested subtitles and their format"""
        ...
    def dl(self, name: str, info: _InfoDict, subtitle: bool = False, test: bool = False) -> bool: ...
    def existing_file(self, filepaths: Iterable[str], *, default_overwrite: bool = True) -> str | None: ...
    def process_info(self, info_dict: _InfoDict) -> None:
        """Process a single resolved IE result. (Modifies it in-place)"""
        ...
    def download(self, url_list: Collection[str]) -> int:
        """Download a given list of URLs."""
        ...
    def download_with_info_file(self, info_filename: str) -> int: ...
    @staticmethod
    def sanitize_info(info_dict: _InfoDict, remove_private_keys: bool = False) -> _InfoDict | None:
        """Sanitize the infodict for converting to json """
        ...
    @staticmethod
    def filter_requested_info(info_dict: _InfoDict, actually_filter: bool = True) -> _InfoDict | None:
        """Alias of sanitize_info for backward compatibility """
        ...
    @staticmethod
    def post_extract(info_dict: _InfoDict) -> None: ...
    def run_pp(self, pp: PostProcessor, infodict: _InfoDict) -> _InfoDict: ...
    def run_all_pps(self, key: str, info: _InfoDict, *, additional_pps: Collection[PostProcessor] | None = None) -> _InfoDict: ...
    def pre_process(
        self, ie_info: _InfoDict, key: str = "pre_process", files_to_move: Mapping[str, Any] | None = None
    ) -> tuple[_InfoDict, list[str] | None]: ...
    def post_process(self, filename: str, info: _InfoDict, files_to_move: Mapping[str, Any] | None = None) -> _InfoDict:
        """Run all the postprocessors on the given file."""
        ...
    def in_download_archive(self, info_dict: _InfoDict) -> bool: ...
    def record_download_archive(self, info_dict: _InfoDict) -> None: ...
    @staticmethod
    def format_resolution(format: Mapping[str, Any], default: str = "unknown") -> str: ...
    def render_formats_table(self, info_dict: _InfoDict) -> str | None: ...
    def render_thumbnails_table(self, info_dict: _InfoDict) -> str | None: ...
    def render_subtitles_table(self, video_id: str, subtitles: Iterable[Mapping[str, Any]]) -> str | None: ...
    def list_formats(self, info_dict: _InfoDict) -> None: ...
    def list_thumbnails(self, info_dict: _InfoDict) -> None: ...
    def list_subtitles(self, video_id: str, subtitles: Iterable[Mapping[str, Any]], name: str = "subtitles") -> None: ...
    def print_debug_header(self) -> None: ...
    @cached_property
    def proxies(self) -> dict[str, Any]:
        """Global proxy configuration"""
        ...
    @cached_property
    def cookiejar(self) -> YoutubeDLCookieJar:
        """Global cookiejar instance"""
        ...
    def urlopen(self, req: Request | str) -> Response:
        """Start an HTTP download """
        ...
    def build_request_director(
        self, handlers: Collection[RequestHandler], preferences: Collection[Any] | None = None
    ) -> RequestDirector: ...
    def encode(self, s: str) -> bytes: ...
    def get_encoding(self) -> str: ...
