from _typeshed import Incomplete
from collections.abc import Iterator

from kafka.util import classproperty

class SlotsBuilder(type):
    def __new__(metacls, name, bases, attrs, **kw): ...

class DataContainer(metaclass=SlotsBuilder):
    __slots__ = ("tags", "unknown_tags", "_version")
    def __init_subclass__(cls, **kwargs) -> None: ...
    tags: set[Incomplete] | None
    unknown_tags: dict[str, Incomplete] | None
    def __init__(self, *args, version=None, **field_vals) -> None: ...
    def __getattr__(self, name): ...
    @property
    def version(self): ...
    def encode(self, *args, **kwargs):
        """Add version= to kwargs, otherwise pass-through to _struct"""
        ...
    def encode_into(self, out, *args, **kwargs) -> None:
        """Buffer-based encode, pass-through to _struct.encode_into"""
        ...
    @classmethod
    def decode(cls, data, **kwargs):
        """Add version= to kwargs, otherwise pass-through to _struct"""
        ...
    @classproperty
    def fields(cls): ...
    def __eq__(self, other) -> bool: ...
    def __iter__(self) -> Iterator[Incomplete]: ...
    def to_dict(self, meta: bool = False, json: bool = True) -> dict[Incomplete, Incomplete]:
        """
        Use meta=True to include top-level version; meta='all' to include all internal versions
        json=False to return raw encoding; json=True (default) to convert values to be json-serializable
        """
        ...
    def __getitem__(self, key: int | slice): ...
