from kafka.metrics.stats.sampled_stat import AbstractSampledStat

class Avg(AbstractSampledStat):
    """An AbstractSampledStat that maintains a simple average over its samples."""
    __slots__ = ("_initial_value", "_samples", "_current")
    def __init__(self) -> None: ...
    def update(self, sample, config, value, now) -> None: ...
    def combine(self, samples, config, now): ...
