from kafka.metrics.stats.sampled_stat import AbstractSampledStat

class Count(AbstractSampledStat):
    """An AbstractSampledStat that maintains a simple count of what it has seen."""
    __slots__ = ("_initial_value", "_samples", "_current")
    def __init__(self) -> None: ...
    def update(self, sample, config, value, now) -> None: ...
    def combine(self, samples, config, now): ...
