"""Rasterio input/output."""

import os
from collections.abc import Iterator, Sequence
from typing import Any, BinaryIO, Final
from typing_extensions import Self, deprecated

import numpy as np
from numpy.typing import DTypeLike, NDArray
from rasterio._affine_types import Affine
from rasterio._base import DatasetBase
from rasterio._path import _ParsedPath, _UnparsedPath
from rasterio._typing import Colormap, CRSInput, Indexes, NumType, ShapeND, WindowInput, _GDALOption, _OpenOption
from rasterio.control import GroundControlPoint
from rasterio.enums import Resampling
from rasterio.rpc import RPC

def validate_resampling(resampling: Resampling) -> None:
    """Validate that the resampling method is compatible of reads/writes."""
    ...
def virtual_file_to_buffer(filename: str) -> bytes:
    """Read content of a virtual file into a Python bytes buffer."""
    ...
def _is_complex_int(dtype: DTypeLike) -> bool: ...
def _getnpdtype(dtype: DTypeLike) -> np.dtype[Any]: ...
def _gdal_typename(dt: DTypeLike) -> str: ...
def _get_gdal_dtype(type_name: DTypeLike) -> int: ...
def _boundless_vrt_doc(
    src_dataset: DatasetBase,
    nodata: float | None = None,
    background: float | None = None,
    hidenodata: bool = False,
    width: int | None = None,
    height: int | None = None,
    transform: Affine | None = None,
    masked: bool = False,
    resampling: Resampling = ...,
) -> str:
    """
    Make a VRT XML document.

    Parameters
    ----------
    src_dataset : Dataset
        The dataset to wrap.
    background : int or float, optional
        The background fill value for the boundless VRT.
    masked : bool
        If True, the src_dataset is replaced by its valid data mask.

    Returns
    -------
    str
        An XML text string.
    """
    ...
def sample_gen(
    dataset: DatasetBase, xy: Sequence[tuple[float, float]], indexes: Indexes | None = None, masked: bool = False
) -> Iterator[NDArray[Any]]:
    """
    Sample pixels from a dataset

    Parameters
    ----------
    dataset : rasterio Dataset
        Opened in "r" mode.
    xy : iterable
        Pairs of x, y coordinates in the dataset's reference system.

        Note: Sorting coordinates can often yield better performance.
        A sort_xy function is provided in this module for convenience.
    indexes : int or list of int
        Indexes of dataset bands to sample.
    masked : bool, default: False
        Whether to mask samples that fall outside the extent of the
        dataset.

    Yields
    ------
    array
        A array of length equal to the number of specified indexes
        containing the dataset values for the bands corresponding to
        those indexes.
    """
    ...

class Statistics:
    """
    Raster band statistics.

    Attributes
    ----------
    min, max, mean, std : float
        Basic stats of a raster band.
    """
    min: float
    max: float
    mean: float
    std: float
    def __init__(self, min: float, max: float, mean: float, std: float) -> None:
        """Method generated by attrs for class Statistics."""
        ...

class DatasetReaderBase(DatasetBase):
    """Provides data and metadata reading methods."""
    def read(
        self,
        indexes: Indexes | None = None,
        out: NDArray[Any] | None = None,
        window: WindowInput | None = None,
        masked: bool = False,
        out_shape: ShapeND | None = None,
        boundless: bool = False,
        resampling: Resampling = ...,
        fill_value: NumType | None = None,
        out_dtype: DTypeLike | None = None,
    ) -> NDArray[Any]:
        """
        Read band data and, optionally, mask as an array.

        A smaller (or larger) region of the dataset may be specified and
        it may be resampled and/or converted to a different data type.

        Parameters
        ----------
        indexes : int or list, optional
            If `indexes` is a list, the result is a 3D array, but is
            a 2D array if it is a band index number.
        out : numpy.ndarray, optional
            As with Numpy ufuncs, this is an optional reference to an
            output array into which data will be placed. If the height
            and width of `out` differ from that of the specified
            window (see below), the raster image will be decimated or
            replicated using the specified resampling method (also see
            below). This parameter cannot be combined with `out_shape`.

            *Note*: the method's return value may be a view on this
            array. In other words, `out` is likely to be an
            incomplete representation of the method's results.
        out_dtype : str or numpy.dtype
            The desired output data type. For example: 'uint8' or
            rasterio.uint16.
        out_shape : tuple, optional
            A tuple describing the shape of a new output array. See
            `out` (above) for notes on image decimation and replication.
            This parameter cannot be combined with `out`.
        window : Window, optional
            The region (slice) of the dataset from which data will be
            read. The default is the entire dataset.
        masked : bool, optional
            If `masked` is `True` the return value will be a masked
            array. Otherwise (the default) the return value will be a
            regular array. Masks will be exactly the inverse of the
            GDAL RFC 15 conforming arrays returned by read_masks().
        boundless : bool, optional (default `False`)
            If `True`, windows that extend beyond the dataset's extent
            are permitted and partially or completely filled arrays will
            be returned as appropriate.
        resampling : Resampling
            By default, pixel values are read raw or interpolated using
            a nearest neighbor algorithm from the band cache. Other
            resampling algorithms may be specified. Resampled pixels
            are not cached.
        fill_value : scalar
            Fill value applied in the `boundless=True` case only. Like
            the fill_value of :class:`numpy.ma.MaskedArray`, should be value
            valid for the dataset's data type.

        Returns
        -------
        Numpy ndarray or a view on a Numpy ndarray

        Raises
        ------
        RasterioIOError
            If the write fails.

        Notes
        -----
        This data is read from the dataset's band cache, which means
        that repeated reads of the same windows may avoid I/O.

        As with Numpy ufuncs, an object is returned even if you use the
        optional `out` argument and the return value shall be
        preferentially used by callers.
        """
        ...
    def read_masks(
        self,
        indexes: Indexes | None = None,
        out: NDArray[Any] | None = None,
        out_shape: ShapeND | None = None,
        window: WindowInput | None = None,
        boundless: bool = False,
        resampling: Resampling = ...,
    ) -> NDArray[Any]:
        """
        Read band masks as an array.

        A smaller (or larger) region of the dataset may be specified and
        it may be resampled and/or converted to a different data type.

        Parameters
        ----------
        indexes : int or list, optional
            If `indexes` is a list, the result is a 3D array, but is
            a 2D array if it is a band index number.
        out : numpy.ndarray, optional
            As with Numpy ufuncs, this is an optional reference to an
            output array into which data will be placed. If the height
            and width of `out` differ from that of the specified
            window (see below), the raster image will be decimated or
            replicated using the specified resampling method (also see
            below). This parameter cannot be combined with `out_shape`.

            *Note*: the method's return value may be a view on this
            array. In other words, `out` is likely to be an
            incomplete representation of the method's results.
        out_shape : tuple, optional
            A tuple describing the shape of a new output array. See
            `out` (above) for notes on image decimation and replication.
            This parameter cannot be combined with `out`.
        window : Window, optional
            The region (slice) of the dataset from which data will be
            read. The default is the entire dataset.
        boundless : bool, optional (default `False`)
            If `True`, windows that extend beyond the dataset's extent
            are permitted and partially or completely filled arrays will
            be returned as appropriate.
        resampling : Resampling
            By default, pixel values are read raw or interpolated using
            a nearest neighbor algorithm from the band cache. Other
            resampling algorithms may be specified. Resampled pixels
            are not cached.

        Returns
        -------
        Numpy ndarray or a view on a Numpy ndarray

        Raises
        ------
        RasterioIOError
            If the write fails.

        Notes
        -----
        This data is read from the dataset's band cache, which means
        that repeated reads of the same windows may avoid I/O.

        As with Numpy ufuncs, an object is returned even if you use the
        optional `out` argument and the return value shall be
        preferentially used by callers.
        """
        ...
    def dataset_mask(
        self,
        out: NDArray[Any] | None = None,
        out_shape: ShapeND | None = None,
        window: WindowInput | None = None,
        boundless: bool = False,
        resampling: Resampling = ...,
    ) -> NDArray[Any]:
        """
        Get the dataset's 2D valid data mask.

        Parameters
        ----------
        out : numpy.ndarray, optional
            As with Numpy ufuncs, this is an optional reference to an
            output array with the same dimensions and shape into which
            data will be placed.

            *Note*: the method's return value may be a view on this
            array. In other words, `out` is likely to be an
            incomplete representation of the method's results.

            Cannot be combined with `out_shape`.

        out_shape : tuple, optional
            A tuple describing the output array's shape.  Allows for decimated
            reads without constructing an output Numpy array.

            Cannot be combined with `out`.

        window : a pair (tuple) of pairs of ints or Window, optional
            The optional `window` argument is a 2 item tuple. The first
            item is a tuple containing the indexes of the rows at which
            the window starts and stops and the second is a tuple
            containing the indexes of the columns at which the window
            starts and stops. For example, ((0, 2), (0, 2)) defines
            a 2x2 window at the upper left of the raster dataset.

        boundless : bool, optional (default `False`)
            If `True`, windows that extend beyond the dataset's extent
            are permitted and partially or completely filled arrays will
            be returned as appropriate.

        resampling : Resampling
            By default, pixel values are read raw or interpolated using
            a nearest neighbor algorithm from the band cache. Other
            resampling algorithms may be specified. Resampled pixels
            are not cached.

        Returns
        -------
        Numpy ndarray or a view on a Numpy ndarray
            The dtype of this array is uint8. 0 = nodata, 255 = valid
            data.

        Notes
        -----
        Note: as with Numpy ufuncs, an object is returned even if you
        use the optional `out` argument and the return value shall be
        preferentially used by callers.

        The dataset mask is calculated based on the individual band
        masks according to the following logic, in order of precedence:

        1. If a .msk file, dataset-wide alpha, or internal mask exists
           it will be used for the dataset mask.
        2. Else if the dataset is a 4-band  with a shadow nodata value, band 4 will be
           used as the dataset mask.
        3. If a nodata value exists, use the binary OR (|) of the band
           masks 4. If no nodata value exists, return a mask filled with
           255.

        Note that this differs from read_masks and GDAL RFC15 in that it
        applies per-dataset, not per-band (see
        https://trac.osgeo.org/gdal/wiki/rfc15_nodatabitmask)
        """
        ...
    def sample(
        self, xy: Sequence[tuple[float, float]], indexes: Indexes | None = None, masked: bool = False
    ) -> Iterator[NDArray[Any]]:
        """
        Get the values of a dataset at certain positions

        Values are from the nearest pixel. They are not interpolated.

        Parameters
        ----------
        xy : iterable
            Pairs of x, y coordinates (floats) in the dataset's
            reference system.
        indexes : int or list of int
            Indexes of dataset bands to sample.
        masked : bool, default: False
            Whether to mask samples that fall outside the extent of the
            dataset.

        Returns
        ------
        iterable
            Arrays of length equal to the number of specified indexes
            containing the dataset values for the bands corresponding to
            those indexes.
        """
        ...
    def stats(self, *, indexes: Indexes | None = None, approx: bool = False) -> list[Statistics]:
        """
        Update stored statistics for all dataset bands.

        If no stats are provided, statistics will be computed for all
        bands of the dataset.

        Parameters
        ----------
        indexes : sequence of ints, optional
            A sequence of band indexes, 1-indexed. If not provided,
            defaults to the indexes of all dataset bands.
        approx : bool, optional. Default: False
            Set to True if approximate, faster computation of statistics
            based on overviews or a subset of tiles is acceptable.

        Returns
        -------
        List of Statistics objects.
        """
        ...
    @deprecated("DatasetReaderBase.statistics() will be removed in 2.0.0; please switch to stats().")
    def statistics(self, bidx: int, approx: bool = False, clear_cache: bool = False) -> Statistics:
        """
        Get min, max, mean, and standard deviation of a raster band.

        Parameters
        ----------
        bidx : int
            The band's index (1-indexed).
        approx : bool, optional
            If True, statistics will be calculated from reduced
            resolution data.
        clear_cache : bool, optional
            If True, saved stats will be deleted and statistics will be
            recomputed. Requires GDAL version >= 3.2.

        Returns
        -------
        Statistics

        Notes
        -----
        GDAL will preferentially use statistics kept in raster metadata
        like images tags or an XML sidecar. If that metadata is out of
        date, the statistics may not correspond to the actual data.

        Additionally, GDAL will save statistics to file metadata as a
        side effect if that metadata does not already exist.
        """
        ...

class MemoryFileBase:
    """Base for a BytesIO-like class backed by an in-memory file."""
    name: str
    mode: str
    closed: bool
    def __init__(
        self,
        file_or_bytes: bytes | BinaryIO | None = None,
        dirname: str | None = None,
        filename: str | None = None,
        ext: str = "",
    ) -> None:
        """
        A file in an in-memory filesystem.

        Parameters
        ----------
        file_or_bytes : file or bytes
            A file opened in binary mode or bytes
        filename : str
            A filename for the in-memory file under /vsimem
        ext : str
            A file extension for the in-memory file under /vsimem. Ignored if
            filename was provided.
        """
        ...
    def __len__(self) -> int:
        """
        Length of the file's buffer in number of bytes.

        Returns
        -------
        int
        """
        ...
    def exists(self) -> bool:
        """
        Test if the in-memory file exists.

        Returns
        -------
        bool
            True if the in-memory file exists.
        """
        ...
    def getbuffer(self) -> memoryview:
        """Return a view on bytes of the file."""
        ...
    def close(self) -> None: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def read(self, size: int = -1) -> bytes:
        """
        Read bytes from MemoryFile.

        Parameters
        ----------
        size : int
            Number of bytes to read. Default is -1 (all bytes).

        Returns
        -------
        bytes
            String of bytes read.
        """
        ...
    def write(self, data: bytes) -> int:
        """
        Write data bytes to MemoryFile.

        Parameters
        ----------
        data : bytes

        Returns
        -------
        int
            Number of bytes written.
        """
        ...

class DatasetWriterBase(DatasetReaderBase):
    """
    Read-write access to raster data and metadata
    
    """
    name: str
    mode: str
    width: int
    height: int
    shape: tuple[int, int]
    driver: str

    def __init__(
        self,
        path: str | os.PathLike[str] | _ParsedPath | _UnparsedPath,
        mode: str,
        driver: str | None = None,
        width: int | None = None,
        height: int | None = None,
        count: int | None = None,
        crs: CRSInput | None = None,
        transform: Affine | None = None,
        dtype: DTypeLike | None = None,
        nodata: float | None = None,
        gcps: Sequence[GroundControlPoint] | None = None,
        rpcs: RPC | None = None,
        sharing: bool = False,
        **kwargs: _OpenOption,
    ) -> None:
        """
        Create a new dataset writer or updater

        Parameters
        ----------
        path : rasterio.path.Path
            A remote or local dataset path.
        mode : str
            'r+' (read/write), 'w' (write), or 'w+' (write/read).
        driver : str, optional
            A short format driver name (e.g. "GTiff" or "JPEG") or a list of
            such names (see GDAL docs at
            http://www.gdal.org/formats_list.html). In 'w' or 'w+' modes
            a single name is required. In 'r' or 'r+' modes the driver can
            usually be omitted. Registered drivers will be tried
            sequentially until a match is found. When multiple drivers are
            available for a format such as JPEG2000, one of them can be
            selected by using this keyword argument.
        width, height : int, optional
            The numbers of rows and columns of the raster dataset. Required
            in 'w' or 'w+' modes, they are ignored in 'r' or 'r+' modes.
        count : int, optional
            The count of dataset bands. Required in 'w' or 'w+' modes, it is
            ignored in 'r' or 'r+' modes.
        crs : str, dict, or CRS; optional
            The coordinate reference system. Required in 'w' or 'w+' modes,
            it is ignored in 'r' or 'r+' modes.
        transform : Affine instance, optional
            Affine transformation mapping the pixel space to geographic
            space. Required in 'w' or 'w+' modes, it is ignored in 'r' or
            'r+' modes.
        dtype : str or numpy.dtype
            The data type for bands. For example: 'uint8' or
            ``rasterio.uint16``. Required in 'w' or 'w+' modes, it is
            ignored in 'r' or 'r+' modes.
        nodata : int, float, or nan; optional
            Defines the pixel value to be interpreted as not valid data.
            Required in 'w' or 'w+' modes, it is ignored in 'r' or 'r+'
            modes.
        gcps : Sequence of GroundControlPoint, optional
            Zero or more ground control points mapping pixel space to
            geographic space locations. Ignored in 'r' or 'r+' modes.
        rpcs : RPC or dict, optional
            Rational polynomial coefficients mapping geographic space (x, y, z)
            coordinates to pixel space coordinates (row, column). If passing a dict,
            should be in a form suitable as input to `RPC.from_gdal` method.
            Ignored in 'r' or 'r+' modes.
        sharing : bool
            A flag that allows sharing of dataset handles. Default is
            `False`. Should be set to `False` in a multithreaded:w program.
        kwargs : optional
            These are passed to format drivers as directives for creating or
            interpreting datasets. For example: in 'w' or 'w+' modes
            a `tiled=True` keyword argument will direct the GeoTIFF format
            driver to create a tiled, rather than striped, TIFF.

        Returns
        -------
        dataset
        """
        ...
    def write(
        self, arr: NDArray[Any], indexes: Indexes | None = None, window: WindowInput | None = None, masked: bool = False
    ) -> None:
        """
        Write the arr array into indexed bands of the dataset.

        If given a Numpy MaskedArray and masked is True, the input's
        data and mask will be written to the dataset's bands and band
        mask. If masked is False, no band mask is written. Instead, the
        input array's masked values are filled with the dataset's nodata
        value (if defined) or the input's own fill value.

        Parameters
        ----------
        arr : array-like
            This may be a :class:`numpy.ma.MaskedArray`.
        indexes : int or list, optional
            Which bands of the dataset to write to. The default is all.
        window : Window, optional
            The region (slice) of the dataset to which arr will be
            written. The default is the entire dataset.
        masked : bool, optional
            Whether or not to write to the dataset's band mask.

        Returns
        -------
        None

        Raises
        ------
        RasterioIOError
            If the write fails.
        """
        ...
    def write_band(self, bidx: int, src: NDArray[Any], window: WindowInput | None = None) -> None:
        """
        Write the src array into the `bidx` band.

        Band indexes begin with 1: read_band(1) returns the first band.

        The optional `window` argument takes a tuple like:

            ((row_start, row_stop), (col_start, col_stop))

        specifying a raster subset to write into.
        """
        ...
    def update_tags(self, bidx: int = 0, ns: str | None = None, **kwargs: _GDALOption) -> None:
        """
        Updates the tags of a dataset or one of its bands.

        Tags are pairs of key and value strings. Tags belong to
        namespaces.  The standard namespaces are: default (None) and
        'IMAGE_STRUCTURE'.  Applications can create their own additional
        namespaces.

        The optional bidx argument can be used to select the dataset
        band. The optional ns argument can be used to select a namespace
        other than the default.
        """
        ...
    def set_band_description(self, bidx: int, value: str) -> None:
        """
        Sets the description of a dataset band.

        Parameters
        ----------
        bidx : int
            Index of the band (starting with 1).

        value: string
            A description of the band.

        Returns
        -------
        None
        """
        ...
    def set_band_unit(self, bidx: int, value: str) -> None:
        """
        Sets the unit of measure of a dataset band.

        Parameters
        ----------
        bidx : int
            Index of the band (starting with 1).
        value : str
            A label for the band's unit of measure such as 'meters' or
            'degC'.  See the Pint project for a suggested list of units.

        Returns
        -------
        None
        """
        ...
    def write_colormap(self, bidx: int, colormap: Colormap) -> None:
        """
        Write a colormap for a band to the dataset.

        A colormap maps pixel values of a single-band dataset to RGB or
        RGBA colors.

        Parameters
        ----------
        bidx : int
            Index of the band (starting with 1).
        colormap : Mapping
            Keys are integers and values are 3 or 4-tuples of ints.

        Returns
        -------
        None
        """
        ...
    def write_mask(self, mask_array: NDArray[Any], window: WindowInput | None = None) -> None:
        """
        Write to the dataset's band mask.

        Values > 0 represent valid data.

        Parameters
        ----------
        mask_array : ndarray
            Values of 0 represent invalid or missing data. Values > 0
            represent valid data.
        window : Window, optional
            A subset of the dataset's band mask.

        Returns
        -------
        None

        Raises
        ------
        RasterioIOError
            When no mask is written.
        """
        ...
    def build_overviews(self, factors: Sequence[int], resampling: Resampling = ...) -> None:
        """
        Build overviews at one or more decimation factors for all
        bands of the dataset.
        """
        ...
    def update_stats(
        self, *, stats: Sequence[Statistics] | None = None, indexes: Indexes | None = None, approx: bool = False
    ) -> None:
        """
        Update stored statistics for all dataset bands.

        If no stats are provided, statistics will be computed for all
        bands of the dataset.

        Parameters
        ----------
        stats : sequence of Statistics, optional
            A sequence of band statistics objects. Will be zipped
            together with the indexes sequence.
        indexes : sequence of ints, optional
            A sequence of band indexes, 1-indexed. If not provided,
            defaults to src.indexes.
        approx : bool, optional. Default: False
            Set to True if approximate, faster computation of statistics
            based on overviews or a subset of tiles is acceptable.

        Returns
        -------
        None
        """
        ...
    def clear_stats(self) -> None:
        """
        Clear stored statistics for all dataset bands.

        Returns
        -------
        None
        """
        ...

class MemoryDataset(DatasetWriterBase):
    def __init__(
        self,
        image: NDArray[Any] | None = None,
        dtype: DTypeLike | None = None,
        count: int = 1,
        width: int | None = None,
        height: int | None = None,
        transform: Affine | None = None,
        gcps: Sequence[GroundControlPoint] | None = None,
        rpcs: RPC | None = None,
        crs: CRSInput | None = None,
    ) -> None:
        """
        Dataset wrapped around in-memory array.

        This class is intended for internal use only within rasterio to
        support IO with GDAL, where a Dataset object is needed.

        MemoryDataset supports the NumPy array interface.

        Parameters
        ----------
        arr : ndarray
            Array to use for dataset
        transform : Transform
            Dataset transform
        gcps : list
            List of GroundControlPoints, a CRS
        rpcs : list
            Dataset rational polynomial coefficients
        crs : CRS
            Dataset coordinate reference system
        copy : bool, optional
            Create an internal copy of the array. If set to False,
            caller must make sure that arr is valid while this object
            lives. Default is to copy only as needed.
        """
        ...
    def __enter__(self) -> Self: ...

class BufferedDatasetWriterBase(DatasetWriterBase):
    def __init__(
        self,
        path: str | os.PathLike[str] | _ParsedPath | _UnparsedPath,
        mode: str = "w",
        driver: str | None = None,
        width: int | None = None,
        height: int | None = None,
        count: int | None = None,
        crs: CRSInput | None = None,
        transform: Affine | None = None,
        dtype: DTypeLike | None = None,
        nodata: float | None = None,
        gcps: Sequence[GroundControlPoint] | None = None,
        rpcs: RPC | None = None,
        sharing: bool = False,
        **kwargs: _OpenOption,
    ) -> None:
        """
        Construct a new dataset

        Parameters
        ----------
        path : rasterio.path.Path
            A remote or local dataset path.
        mode : str, optional
            'r' (read, the default), 'r+' (read/write), 'w' (write), or
            'w+' (write/read).
        driver : str, optional
            A short format driver name (e.g. "GTiff" or "JPEG") or a list of
            such names (see GDAL docs at
            http://www.gdal.org/formats_list.html). In 'w' or 'w+' modes
            a single name is required. In 'r' or 'r+' modes the driver can
            usually be omitted. Registered drivers will be tried
            sequentially until a match is found. When multiple drivers are
            available for a format such as JPEG2000, one of them can be
            selected by using this keyword argument.
        width, height : int, optional
            The numbers of rows and columns of the raster dataset. Required
            in 'w' or 'w+' modes, they are ignored in 'r' or 'r+' modes.
        count : int, optional
            The count of dataset bands. Required in 'w' or 'w+' modes, it is
            ignored in 'r' or 'r+' modes.
        crs : str, dict, or CRS; optional
            The coordinate reference system. Required in 'w' or 'w+' modes,
            it is ignored in 'r' or 'r+' modes.
        transform : Affine instance, optional
            Affine transformation mapping the pixel space to geographic
            space. Required in 'w' or 'w+' modes, it is ignored in 'r' or
            'r+' modes.
        dtype : str or numpy.dtype
            The data type for bands. For example: 'uint8' or
            ``rasterio.uint16``. Required in 'w' or 'w+' modes, it is
            ignored in 'r' or 'r+' modes.
        nodata : int, float, or nan; optional
            Defines the pixel value to be interpreted as not valid data.
            Required in 'w' or 'w+' modes, it is ignored in 'r' or 'r+'
            modes.
        sharing : bool
            A flag that allows sharing of dataset handles. Default is
            `False`. Should be set to `False` in a multithreaded program.
        kwargs : optional
            These are passed to format drivers as directives for creating or
            interpreting datasets. For example: in 'w' or 'w+' modes
            a `tiled=True` keyword argument will direct the GeoTIFF format
            driver to create a tiled, rather than striped, TIFF.
            driver : str or list of str, optional
            A single driver name or a list of names to be considered when
            opening the dataset. Required to create a new dataset.

        Returns
        -------
        dataset
        """
        ...
    def stop(self) -> None: ...

int8: Final[str]
uint8: Final[str]
