"""
Dataset paths, identifiers, and filenames

Note: this module is not part of Rasterio's API. It is for internal use
only.
"""

import os
from typing import Any, Final
from typing_extensions import Self

SCHEMES: Final[dict[str, str]]
ARCHIVESCHEMES: Final[type[set[Any]]]
CURLSCHEMES: Final[set[str]]
REMOTESCHEMES: Final[set[str]]

class _Path:
    """Base class for dataset paths"""
    def as_vsi(self) -> str: ...

class _ParsedPath(_Path):
    """
    Result of parsing a dataset URI/Path

    Attributes
    ----------
    path : str
        Parsed path. Includes the hostname and query string in the case
        of a URI.
    archive : str
        Parsed archive path.
    scheme : str
        URI scheme such as "https" or "zip+s3".
    """
    path: str
    archive: str | None
    scheme: str | None
    def __init__(self, path: str, archive: str | None, scheme: str | None) -> None:
        """Method generated by attrs for class _ParsedPath."""
        ...
    @classmethod
    def from_uri(cls, uri: str) -> Self: ...
    @property
    def name(self) -> str:
        """The parsed path's original URI"""
        ...
    @property
    def is_remote(self) -> bool:
        """Test if the path is a remote, network URI"""
        ...
    @property
    def is_local(self) -> bool:
        """Test if the path is a local URI"""
        ...

class _UnparsedPath(_Path):
    """
    Encapsulates legacy GDAL filenames

    Attributes
    ----------
    path : str
        The legacy GDAL filename.
    """
    path: str
    def __init__(self, path: str) -> None:
        """Method generated by attrs for class _UnparsedPath."""
        ...
    @property
    def name(self) -> str:
        """The unparsed path's original path"""
        ...

def _parse_path(path: str | os.PathLike[str] | _Path) -> _ParsedPath | _UnparsedPath:
    """
    Parse a dataset's identifier or path into its parts

    Parameters
    ----------
    path : str or path-like object
        The path to be parsed.

    Returns
    -------
    ParsedPath or UnparsedPath

    Notes
    -----
    When legacy GDAL filenames are encountered, they will be returned
    in a UnparsedPath.
    """
    ...
def _vsi_path(path: _Path) -> str:
    """
    Convert a parsed path to a GDAL VSI path

    Parameters
    ----------
    path : Path
        A ParsedPath or UnparsedPath object.

    Returns
    -------
    str
    """
    ...
