"""Errors and Warnings."""

from click import FileError

class RasterioError(Exception):
    """Root exception class"""
    ...
class InvalidArrayError(RasterioError):
    """Raised when methods are passed invalid arrays"""
    ...
class WindowError(RasterioError):
    """Raised when errors occur during window operations"""
    ...
class CRSError(ValueError):
    """
    Raised when a CRS string or mapping is invalid or cannot serve
    to define a coordinate transformation.
    """
    ...
class EnvError(RasterioError):
    """
    Raised when the state of GDAL/AWS environment cannot be created
    or modified.
    """
    ...
class DriverCapabilityError(RasterioError, ValueError):
    """Raised when a format driver can't a feature such as writing."""
    ...
class DriverRegistrationError(ValueError):
    """Raised when a format driver is requested but is not registered."""
    ...

class FileOverwriteError(FileError):
    """Raised when Rasterio's CLI refuses to clobber output files."""
    def __init__(self, message: str) -> None:
        """Raise FileOverwriteError with message as hint."""
        ...

class RasterioIOError(RasterioError, OSError): ...
class NodataShadowWarning(UserWarning): ...
class NotGeoreferencedWarning(UserWarning): ...
class TransformWarning(UserWarning): ...
class RPCError(ValueError): ...
class InvalidShapeError(RasterioError, ValueError): ...
class ShapeSkipWarning(UserWarning): ...
class GDALBehaviorChangeException(RuntimeError): ...
class GDALOptionNotImplementedError(RasterioError): ...
class GDALVersionError(RasterioError): ...
class WindowEvaluationError(ValueError): ...
class RasterioDeprecationWarning(FutureWarning): ...
class RasterBlockError(RasterioError): ...
class BandOverviewError(UserWarning): ...
class WarpOptionsError(RasterioError): ...
class UnsupportedOperation(RasterioError): ...
class OverviewCreationError(RasterioError): ...
class DatasetAttributeError(RasterioError, NotImplementedError): ...
class PathError(RasterioError): ...
class ResamplingAlgorithmError(RasterioError): ...
class TransformError(RasterioError): ...
class WarpedVRTError(RasterioError): ...
class DatasetIOShapeError(RasterioError): ...
class WarpOperationError(RasterioError): ...
class StatisticsError(RasterioError): ...
class OpenerRegistrationError(RasterioError): ...
class MergeError(RasterioError): ...
class StackError(RasterioError): ...
