from _typeshed import Incomplete
from typing_extensions import Self

from .base import BaseField
from .codegen import CodegenContext

class StructField(BaseField):
    @classmethod
    def parse_json(cls, json) -> Self | None: ...
    def __init__(self, json) -> None: ...
    @property
    def fields(self) -> dict[Incomplete, Incomplete]: ...
    def is_struct(self): ...
    def has_data_class(self) -> bool: ...
    def set_data_class(self, data_class) -> None: ...
    @property
    def data_class(self): ...
    def __call__(self, *args, **kw): ...
    def tagged_fields(self, version): ...
    def untagged_fields(self, version): ...
    def encode(self, item, version=None, compact: bool = False, tagged: bool = False) -> bytes: ...
    def emit_encode_into(
        self, ctx, item_expr, indent, version=None, compact: bool = False, tagged: bool = False, tuple_access: bool = False
    ) -> None: ...
    def encode_into(self, item, out, version=None, compact: bool = False, tagged: bool = False) -> None: ...
    def encode_into__optimized_context(self, version, compact: bool = False, tagged: bool = False) -> CodegenContext: ...
    def compiled_encode_into(self, version, compact: bool = False, tagged: bool = False):
        """
        Return a compiled flat encode function for this struct+version.

        Lazily compiled on first call and cached. The returned function has
        signature: f(item, out) where out is an EncodeBuffer.
        """
        ...
    def emit_decode_from(self, ctx, var_name, indent, version=None, compact: bool = False, tagged: bool = False) -> None:
        """
        Emit decode code that creates a DataContainer via __new__ + direct slot assignment.

        Batches adjacent batchable fields into single unpack_from calls.
        """
        ...
    def compiled_decode_from(self, version, compact: bool = False, tagged: bool = False, data_class=None):
        """
        Return a compiled flat decode function for this struct+version.

        Lazily compiled on first call and cached. The returned function has
        signature: f(data, pos) -> (obj, pos) where data is a memoryview/bytes.
        data_class overrides self.data_class for the top-level object (needed
        to resolve weakref proxies on ApiMessage classes).
        """
        ...
    def decode(self, data, version=None, compact: bool = False, tagged: bool = False, data_class=None): ...
    def __len__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
